import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/nav/navbar'
import Banner from '../components/banner/banner'
import Card from '../components/card/card'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>K-FLIX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>K-Flix</h1> */}
      <Navbar username="cebreros@gmail.com" />
      <Banner 
        title="LOONA"
        subTitle="12 members"
        imgUrl="/static/loonaflix.webp"
      />
      <Card imgUrl="/static/loonaflix.webp" size="large" />
      <Card imgUrl="/static/loonaflix.webp" size="medium" />

      <Card imgUrl="/static/loonaflix.webp" size="small" />

    </div>
  )
}
