import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Navbar from '../../components/nav/navbar'
import NoVideoBanner from '../../components/banner/no-video-banner'
import SectionCards from '../../components/card/section-cards'

import {getVideos} from "../../lib/videos"
import { getMembers } from '../../lib/groups'

export async function getServerSideProps(context) {
  const name = context.params.groupId
  const groupVideos = await getVideos(`${name} music videos`)
  const members =  getMembers(name)
  console.log({members});
  const size = members ? members.length > 8 ? "medium" : "large" : ""
  return {
    props: { groupVideos, name, members, size},
  }
}
export default function Home({groupVideos, name, members, size}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>K-FLIX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>K-Flix</h1> */}
      <div className={styles.main}>
        <Navbar />
        <NoVideoBanner 
          imgUrl={`/static/groupBanner/${name}.webp`}
        />
        <div className={styles.sectionWrapper}>
          {members && <SectionCards title="MEMBERS" videos={members} size={size}/>}
          <SectionCards title="VIDEOS" videos={groupVideos} size="small"/>
        </div>

      </div>

    </div>
  )
}
